name: Test deployment

env:
  APP_URL: ${{ vars.APP_URL }}
  BASE_URL: ${{ vars.BASE_URL }}
  TAILING_SLASH: ${{ vars.TAILING_SLASH }}
  PROJECT_NAME: ${{ vars.PROJECT_NAME }}
  ORGANIZATION_NAME: ${{ vars.ORGANIZATION_NAME }}

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Prepare .env file
        run: mv .env.deploy .env
      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build